config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get '/login', to: "home#new"
  post '/login', to: 'home#create'
  delete "/logout", to: "home#destroy"

  resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :user_courses, dependent: :destroy
  has_many :users, through: :users_course
  has_many :lessions_courses, dependent: :destroy
  has_many :lessions, through: :lessions_courses
  scope :sort_by_created, ->{order(created_at: :desc)}
end

app/models/lession.rb
class Lession < ApplicationRecord
  has_many :lessions_courses, dependent: :destroy
  has_many :courses, through: :lessions_courses
end

app/models/lessions_course.rb
class LessionsCourse < ApplicationRecord
  belongs_to :course
  belongs_to :lession
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_courses, dependent: :destroy
  has_many :courses, through: :user_courses, dependent: :destroy
  has_secure_password
end

app/models/users_course.rb
class UsersCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  protect_from_forgery with: :exception
  include HomeHelper

  private

  def default_url_options
    {locale: I18n.locale}
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.sort_by_created.paginate(page: params[:page])
  end

  def show
    @course = Course.find_by(id: params[:id])
    return if @course

    flash[:warning] = t "courses.not_found"
    redirect_to courses_path
  end

  def new
    check_exists_course
  end

  def edit
    check_exists_course
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course
    else
      render :new
    end
  end

  def update
    @course = Course.find_by(id: params[:id])
    if @course&.update(course_params)
      redirect_to @course
    else
      flash[:warning] = t "courses.not_found"
      render :edit
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :image)
  end

  def check_exists_course
    @course = Course.find_by(id: params[:id])
    return if @course

    flash[:warning] = t "courses.not_found"
    redirect_to courses_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(user_name: login_params[:user_name])
    if @user&.authenticate(login_params[:password])
      login_in @user
      redirect_to courses_path
    else
      render root_url
    end
  end

  def destroy
    logout
    redirect_to root_url
  end

  private

  def login_params
    params.require(:session).permit(:user_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def login_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/courses/_course.html.erb
<div class="card cardCustom">
    <%= image_tag(course.image ? course.image : "", class: "card-img-top imageHeight") %>
    <div class="card-body">
      <h5 class="card-title"><%= course.name %></h5>
      <p class="card-text"><%= course.description %></p>
    </div>
    <div class="d-flex justify-content-around">
      <%= link_to t("action.show"), course %>
      <%= link_to t("action.edit"), edit_course_path(course) %>
      <%= link_to t("action.delete"), course, method: :delete, data: { confirm: t("mess.sure") } %>
    </div>
</div>

app/views/courses/_form.html.erb
<div class="container">
  <%= form_with(model: course) do |form| %>
    <div class="form-group">
      <%= form.label t "courses.name" %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= form.label t "courses.description" %>
      <%= form.text_field :description, class: "form-control",  required: true %>
    </div>

    <div class="form-group">
      <%= form.label t "courses.image" %>
      <%= form.text_field :image, class: "form-control", required: true %>
    </div>

    <div class="actions">
      <%= form.submit t("courses.create"), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/courses/edit.html.erb
<%= render "form", course: @course %>
<%= link_to t("action.show"), @course %>

app/views/courses/index.html.erb
<% if @courses.present? %>
    <div class="container listCourses">   
        <%= render partial: "course", collection: @courses %>
    </div>
    <br>
    <%= will_paginate %>
    <%= link_to t("courses.new"), new_course_path, class: "btn " %>
<% end %>

app/views/courses/new.html.erb
<div class="container">
  <h1><%= t "courses.create" %></h1>
  <%= render "form", course: @course %>
</div>

app/views/courses/show.html.erb
<%= render "course", course: @course %>

app/views/home/_form.html.erb
<div class="container card">
  <div class="card-body">
    <%= form_for(:session, url: login_path) do |form| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% user.errors.each do |error| %>
              <li>
                <%= error.full_message %>
              </li>
              <% end %>
          </ul>
        </div>
        <% end %>
          <div class="form-group">
            <%= form.label :name %>
              <%= form.text_field :user_name, class: "form-control" , :required=> true %>
          </div>
          <div class="form-group">
            <%= form.label :password %>
              <%= form.text_field :password, class: "form-control" , :required=> true %>
          </div>

          <div class="actions">
            <%= form.submit t("layouts.login"), class: "btn btn-primary" %>
          </div>
          <% end %>
  </div>
</div>

app/views/home/new.html.erb
<%= render 'form' , user: @user %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to t("home.e_learning") , root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto">
        <%if logged_in? %>
          <li class="nav-item active">
            <a class="nav-link" href="#">
              <%= logged_in?; current_user&.name %> <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item active">
            <link_to class="nav-link" , home_path>
              <%= t "courses.courses" %> <span class="sr-only"></span>
            </link_to>
          </li>
          <% end %>
      </ul>

      <% unless logged_in? %>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
          <%= link_to t("layouts.sign_in"), new_user_path %>
        </button>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
          <%= link_to t("layouts.login"), login_path %>
        </button>
        <% else %>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <%= link_to t("layouts.logout"), logout_path, method: :delete %>
          </button>
          <%end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t "home.e_learning_desctiption" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all" , "data-turbolinks-track": "reload" %>
  <%#= javascript_pack_tag "application" , "data-turbolinks-track": "reload" %>
</head>

<body>
  <div class="controller">
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<div class="container card">
  <div class="card-body">
    <%= form_for @user do |form| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% user.errors.each do |error| %>
              <li>
                <%= error.full_message %>
              </li>
              <% end %>
          </ul>
        </div>
        <% end %>
          <div class="form-group">
            <%= form.label :name %>
              <%= form.text_field :name, class: "form-control" , :required=> true %>
          </div>
          <div class="form-group">
            <%= form.label :email %>
              <%= form.email_field :email, class: "form-control" , :required=> true %>
          </div>
          <div class="form-group">
            <%= form.label :user_name %>
              <%= form.text_field :user_name, class: "form-control" , :required=> true %>
          </div>
          <div class="form-group">
            <%= form.label :password %>
              <%= form.text_field :password, class: "form-control" , :required=> true %>
          </div>
          <div class="form-group">
            <%= form.label :password_confirmation %>
              <%= form.text_field :password_confirmation, class: "form-control" , :required=> true %>
          </div>
          <div class="actions">
            <%= form.submit t("layouts.sign_in"), class: "btn btn-primary" %>
          </div>
          <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' , user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>